# Generated by Django 4.1.1 on 2022-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lame', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
