# Generated by Django 4.1.1 on 2022-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='lame',
            new_name='lname',
        ),
    ]
